[build]
  publish = "public"  # Changed from "/" to "public"
  command = ""  # No build command needed for static site

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
from = "/feedback"
to = "/feedback.html"
status = 200

[[redirects]]
  from = "/privacy-policy"
  to = "/privacy-policy.html"
  status = 200

[[redirects]]
  from = "/data-deletion"
  to = "/data-deletion.html"
  status = 200